const categories = [
  {
    id: 1,
    name_en: "Cloth",
    name_ar: "ملابس",
    slug: "mens-clothing",
    image: "/images/categories/Cloth.webp",
    productCount: 42,
  },
  {
    id: 3,
    name_en: "Jewelry",
    name_ar: "مجوهرات",
    slug: "jewelry",
    image: "/images/categories/Jewelry11.jpg",
    productCount: 38,
  },
  {
    id: 4,
    name_en: "Electronics",
    name_ar: "إلكترونيات",
    slug: "electronics",
    image: "/images/categories/ELECTRONICS.jpg",
    productCount: 64,
  },
  {
    id: 5,
    name_en: "Shoes",
    name_ar: "أحذية",
    slug: "shoes",
    image: "/images/categories/SHOES.jpg",
    productCount: 29,
  },
  {
    id: 6,
    name_en: "Bags & Accessories",
    name_ar: "حقائب وإكسسوارات",
    slug: "bags-and-accessories",
    image: "/images/categories/bags.avif",
    productCount: 22,
  },
  {
    id: 8,
    name_en: "Home & Kitchen",
    name_ar: "المنزل والمطبخ",
    slug: "home-and-kitchen",
    image: "/images/categories/Home & Kitchen.png",
    productCount: 47,
  },
  {
    id: 9,
    name_en: "Beauty & Cosmetics",
    name_ar: "الجمال ومستحضرات التجميل",
    slug: "beauty-and-cosmetics",
    image: "/images/categories/Beauty & Cosmetics.webp",
    productCount: 33,
  },
  {
    id: 10,
    name_en: "Sports & Outdoors",
    name_ar: "الرياضة والهواء الطلق",
    slug: "sports-and-outdoors",
    image: "/images/categories/Sports & Outdoors.jpg",
    productCount: 41,
  },
  {
    id: 11,
    name_en: "Toys & Games",
    name_ar: "ألعاب الأطفال",
    slug: "toys-and-games",
    image: "/images/categories/Toys & Games.png",
    productCount: 27,
  },
  {
    id: 12,
    name_en: "Books & Stationery",
    name_ar: "الكتب والقرطاسية",
    slug: "books-and-stationery",
    image: "/images/categories/Books & Stationery.jpg",
    productCount: 35,
  },
  {
    id: 14,
    name_en: "Furniture",
    name_ar: "أثاث",
    slug: "furniture",
    image: "/images/categories/Furniture.jpg",
    productCount: 19,
  },
];

export default categories;
