const products = [
  // 🧥 CLOTH
  {
    id: 1,
    category: "Cloth",
    title_en: "Men's Classic Denim Jacket",
    title_ar: "جاكيت جينز كلاسيكي للرجال",
    price: 39.99,
    oldPrice: 49.99,
    image: "/images/Cloth/Men's Classic Denim Jacket.jpg",
    description_en: "Stylish men's denim jacket made from high-quality cotton blend. Perfect for casual wear and layering during cool seasons. Features classic button closure, chest pockets, and durable stitching. Comfortable, versatile, and never goes out of fashion. Ideal for streetwear lovers and trendsetters alike.",
    description_ar: "Stylish men's denim jacket made from high-quality cotton blend. Perfect for casual wear and layering during cool seasons. Features classic button closure, chest pockets, and durable stitching. Comfortable, versatile, and never goes out of fashion. Ideal for streetwear lovers and trendsetters alike. (وصف عربي)",
    sold: 124,
    rating: 4.7,
    quntity: 15,
    about_en: "A timeless denim jacket designed for comfort and style. Made with premium materials to ensure long-lasting wear. Pair it with jeans or chinos for an effortlessly cool look every day.",
    about_ar: "A timeless denim jacket designed for comfort and style. Made with premium materials to ensure long-lasting wear. Pair it with jeans or chinos for an effortlessly cool look every day. (نبذة بالعربي)",
    size: "large",
    color: ["Blue", "Black"],
  },
  {
    id: 2,
    category: "Cloth",
    title_en: "Casual Cotton T-Shirt",
    title_ar: "تيشيرت قطني كاجوال",
    price: 15.00,
    oldPrice: 19.00,
    image: "/images/Cloth/Casual Cotton T-Shirt.webp",
    description_en: "Soft cotton T-shirt offering maximum comfort and breathability. Minimalist design perfect for everyday wear and layering. Machine washable and durable.",
    description_ar: "Soft cotton T-shirt offering maximum comfort and breathability. Minimalist design perfect for everyday wear and layering. Machine washable and durable. (وصف عربي)",
    sold: 210,
    rating: 4.8,
    quntity: 40,
    about_en: "A must-have casual tee that fits any outfit. Lightweight, comfortable, and available in classic colors for all-day wear.",
    about_ar: "A must-have casual tee that fits any outfit. Lightweight, comfortable, and available in classic colors for all-day wear. (نبذة بالعربي)",
    size: "medium",
    color: ["White", "Gray", "Black"],
  },
  {
    id: 3,
    category: "Cloth",
    title_en: "Slim Fit Jeans",
    title_ar: "جينز بقصة ضيقة",
    price: 42.00,
    oldPrice: 52.00,
    image: "/images/Cloth/Slim Fit Jeans.webp",
    description_en: "High-quality slim-fit jeans crafted from stretchable denim fabric. Modern look with 5-pocket design and sturdy zipper closure.",
    description_ar: "High-quality slim-fit jeans crafted from stretchable denim fabric. Modern look with 5-pocket design and sturdy zipper closure. (وصف عربي)",
    sold: 176,
    rating: 4.6,
    quntity: 20,
    about_en: "Stay stylish and comfortable with these premium slim-fit jeans. Perfect for casual and semi-formal outfits.",
    about_ar: "Stay stylish and comfortable with these premium slim-fit jeans. Perfect for casual and semi-formal outfits. (نبذة بالعربي)",
    size: "large",
    color: ["Blue", "Dark Blue"],
  },
  {
    id: 4,
    category: "Cloth",
    title_en: "Women's Summer Dress",
    title_ar: "فستان صيفي للنساء",
    price: 34.99,
    oldPrice: 44.99,
    image: "/images/Cloth/Women's Summer Dress.jpg",
    description_en: "Lightweight floral summer dress with adjustable straps. Breathable fabric ideal for hot weather and casual outings.",
    description_ar: "Lightweight floral summer dress with adjustable straps. Breathable fabric ideal for hot weather and casual outings. (وصف عربي)",
    sold: 98,
    rating: 4.7,
    quntity: 18,
    about_en: "Embrace summer vibes with this elegant floral dress. Stylish, comfortable, and perfect for any sunny day.",
    about_ar: "Embrace summer vibes with this elegant floral dress. Stylish, comfortable, and perfect for any sunny day. (نبذة بالعربي)",
    size: "medium",
    color: ["Red", "Yellow"],
  },
  {
    id: 5,
    category: "Cloth",
    title_en: "Men's Hoodie Classic Fit",
    title_ar: "هودي رجالي كلاسيكي",
    price: 29.99,
    oldPrice: 39.99,
    image: "/images/Cloth/Men's Hoodie Classic Fit.jpg",
    description_en: "Comfortable fleece hoodie designed for warmth and style. Features adjustable drawstring and kangaroo pocket.",
    description_ar: "Comfortable fleece hoodie designed for warmth and style. Features adjustable drawstring and kangaroo pocket. (وصف عربي)",
    sold: 165,
    rating: 4.8,
    quntity: 25,
    about_en: "A cozy hoodie made for everyday comfort. Ideal for workouts, casual wear, and cool weather.",
    about_ar: "A cozy hoodie made for everyday comfort. Ideal for workouts, casual wear, and cool weather. (نبذة بالعربي)",
    size: "large",
    color: ["Black", "Gray"],
  },

  // 💍 JEWELRY
  {
    id: 6,
    category: "Jewelry",
    title_en: "Elegant Silver Necklace",
    title_ar: "قلادة فضية أنيقة",
    price: 59.00,
    oldPrice: 75.00,
    image: "/images/Jewelry/Elegant Silver Necklace.webp",
    description_en: "Elegant sterling silver necklace with minimalist pendant design. Polished finish adds a subtle shine suitable for any outfit.",
    description_ar: "Elegant sterling silver necklace with minimalist pendant design. Polished finish adds a subtle shine suitable for any outfit. (وصف عربي)",
    sold: 98,
    rating: 4.8,
    quntity: 12,
    about_en: "Add sophistication to your style with this elegant silver necklace. Complements both formal and casual looks.",
    about_ar: "Add sophistication to your style with this elegant silver necklace. Complements both formal and casual looks. (نبذة بالعربي)",
    size: "medium",
    color: ["Silver"],
  },
  {
    id: 7,
    category: "Jewelry",
    title_en: "Gold Hoop Earrings",
    title_ar: "أقراط ذهبية دائرية",
    price: 49.00,
    oldPrice: 59.00,
    image: "/images/Jewelry/Gold Hoop Earrings.jpg",
    description_en: "Classic 18K gold-plated hoop earrings with secure latch closure. Lightweight and hypoallergenic for all-day comfort.",
    description_ar: "Classic 18K gold-plated hoop earrings with secure latch closure. Lightweight and hypoallergenic for all-day comfort. (وصف عربي)",
    sold: 132,
    rating: 4.7,
    quntity: 20,
    about_en: "Timeless elegance in a simple design. Perfect for adding a touch of luxury to your daily wear.",
    about_ar: "Timeless elegance in a simple design. Perfect for adding a touch of luxury to your daily wear. (نبذة بالعربي)",
    size: "small",
    color: ["Gold"],
  },
  {
    id: 8,
    category: "Jewelry",
    title_en: "Diamond Engagement Ring",
    title_ar: "خاتم خطوبة ماسي",
    price: 299.00,
    oldPrice: 359.00,
    image: "/images/Jewelry/Diamond Engagement Ring.jpg",
    description_en: "Stunning engagement ring featuring a high-quality cubic zirconia stone. Sparkles brilliantly like a real diamond.",
    description_ar: "Stunning engagement ring featuring a high-quality cubic zirconia stone. Sparkles brilliantly like a real diamond. (وصف عربي)",
    sold: 54,
    rating: 4.9,
    quntity: 5,
    about_en: "Celebrate love with this elegant and timeless diamond-style ring. Designed to impress and last a lifetime.",
    about_ar: "Celebrate love with this elegant and timeless diamond-style ring. Designed to impress and last a lifetime. (نبذة بالعربي)",
    size: "small",
    color: ["Silver"],
  },
  {
    id: 9,
    category: "Jewelry",
    title_en: "Leather Bracelet Set",
    title_ar: "مجموعة أساور جلدية",
    price: 25.00,
    oldPrice: 32.00,
    image: "/images/Jewelry/Leather Bracelet Set.webp",
    description_en: "Set of three adjustable leather bracelets with metal accents. Perfect for casual wear and gifting.",
    description_ar: "Set of three adjustable leather bracelets with metal accents. Perfect for casual wear and gifting. (وصف عربي)",
    sold: 176,
    rating: 4.5,
    quntity: 30,
    about_en: "Add an edgy touch to your style with these versatile leather bracelets. Comfortable and stylish for everyday wear.",
    about_ar: "Add an edgy touch to your style with these versatile leather bracelets. Comfortable and stylish for everyday wear. (نبذة بالعربي)",
    size: "medium",
    color: ["Brown", "Black"],
  },
  {
    id: 10,
    category: "Jewelry",
    title_en: "Pearl Drop Earrings",
    title_ar: "أقراط لؤلؤ متدلية",
    price: 39.00,
    oldPrice: 49.00,
    image: "/images/Jewelry/Pearl Drop Earrings.webp",
    description_en: "Elegant pearl earrings with gold-tone base. Perfect accessory for formal events or everyday elegance.",
    description_ar: "Elegant pearl earrings with gold-tone base. Perfect accessory for formal events or everyday elegance. (وصف عربي)",
    sold: 67,
    rating: 4.8,
    quntity: 15,
    about_en: "Refined and classic — these pearl earrings bring timeless grace to any outfit.",
    about_ar: "Refined and classic — these pearl earrings bring timeless grace to any outfit. (نبذة بالعربي)",
    size: "small",
    color: ["White", "Gold"],
  },

  // 📱 ELECTRONICS
  {
    id: 11,
    category: "Electronics",
    title_en: "Wireless Bluetooth Earbuds",
    title_ar: "سماعات بلوتوث لاسلكية",
    price: 69.00,
    oldPrice: 89.00,
    image: "/images/Electronics/Wireless Bluetooth Earbuds.jpg",
    description_en: "High-quality wireless earbuds with noise-cancelling technology. Deliver clear sound and deep bass for immersive listening.",
    description_ar: "High-quality wireless earbuds with noise-cancelling technology. Deliver clear sound and deep bass for immersive listening. (وصف عربي)",
    sold: 312,
    rating: 4.6,
    quntity: 25,
    about_en: "Experience freedom and clarity with our wireless Bluetooth earbuds. Seamless connectivity and powerful audio.",
    about_ar: "Experience freedom and clarity with our wireless Bluetooth earbuds. Seamless connectivity and powerful audio. (نبذة بالعربي)",
    size: "small",
    color: ["White", "Black"],
  },
  {
    id: 12,
    category: "Electronics",
    title_en: "Smartphone X9 Pro",
    title_ar: "هاتف ذكي X9 برو",
    price: 599.00,
    oldPrice: 699.00,
    image: "/images/Electronics/Smartphone X9 Pro.jpeg",
    description_en: "Flagship smartphone with AMOLED display, 128GB storage, and 50MP camera. Sleek design and fast performance.",
    description_ar: "Flagship smartphone with AMOLED display, 128GB storage, and 50MP camera. Sleek design and fast performance. (وصف عربي)",
    sold: 425,
    rating: 4.7,
    quntity: 15,
    about_en: "Power meets style in this high-performance smartphone. Capture every moment with stunning clarity.",
    about_ar: "Power meets style in this high-performance smartphone. Capture every moment with stunning clarity. (نبذة بالعربي)",
    size: "medium",
    color: ["Black", "Blue"],
  },
  {
    id: 13,
    category: "Electronics",
    title_en: "Smart Watch FitBand 2",
    title_ar: "ساعة ذكية فيت باند 2",
    price: 79.00,
    oldPrice: 99.00,
    image: "/images/Electronics/Smart Watch FitBand 2.webp" ,
    description_en: "Fitness smartwatch with step, heart rate, and sleep tracking. Long battery life and water resistance.",
    description_ar: "Fitness smartwatch with step, heart rate, and sleep tracking. Long battery life and water resistance. (وصف عربي)",
    sold: 276,
    rating: 4.8,
    quntity: 22,
    about_en: "Track your health and fitness with precision using FitBand 2. Lightweight, stylish, and reliable.",
    about_ar: "Track your health and fitness with precision using FitBand 2. Lightweight, stylish, and reliable. (نبذة بالعربي)",
    size: "medium",
    color: ["Black", "Pink"],
  },
  {
    id: 14,
    category: "Electronics",
    title_en: "Gaming Headset X5",
    title_ar: "سماعة ألعاب X5",
    price: 59.00,
    oldPrice: 79.00,
    image: "/images/Electronics/Gaming Headset X5.avif",
    description_en: "Immersive over-ear gaming headset with noise isolation and RGB lighting. Compatible with PC and consoles.",
    description_ar: "Immersive over-ear gaming headset with noise isolation and RGB lighting. Compatible with PC and consoles. (وصف عربي)",
    sold: 154,
    rating: 4.6,
    quntity: 20,
    about_en: "Take your gaming to the next level with crystal-clear sound and comfort. Designed for long gaming sessions.",
    about_ar: "Take your gaming to the next level with crystal-clear sound and comfort. Designed for long gaming sessions. (نبذة بالعربي)",
    size: "large",
    color: ["Black", "Red"],
  },
  {
    id: 15,
    category: "Electronics",
    title_en: "Portable Bluetooth Speaker",
    title_ar: "مكبر صوت بلوتوث محمول",
    price: 45.00,
    oldPrice: 55.00,
    image: "/images/Electronics/Portable Bluetooth Speaker.jpg",
    description_en: "Compact wireless speaker with deep bass and clear sound. 10-hour battery life and water-resistant build.",
    description_ar: "Compact wireless speaker with deep bass and clear sound. 10-hour battery life and water-resistant build. (وصف عربي)",
    sold: 218,
    rating: 4.7,
    quntity: 30,
    about_en: "Enjoy your music anywhere with this portable and powerful speaker. Perfect for travel and outdoor use.",
    about_ar: "Enjoy your music anywhere with this portable and powerful speaker. Perfect for travel and outdoor use. (نبذة بالعربي)",
    size: "medium",
    color: ["Blue", "Black"],
  },

  // 👟 SHOES
  {
    id: 16,
    category: "Shoes",
    title_en: "Running Sneakers Pro X1",
    title_ar: "حذاء جري برو X1",
    price: 79.99,
    oldPrice: 99.99,
    image: "/images/Shoes/Running Sneakers Pro X1.webp",
    description_en: "Lightweight running shoes designed for comfort and performance. Breathable mesh upper keeps your feet cool and dry.",
    description_ar: "Lightweight running shoes designed for comfort and performance. Breathable mesh upper keeps your feet cool and dry. (وصف عربي)",
    sold: 157,
    rating: 4.5,
    quntity: 20,
    about_en: "Run faster and longer with our Pro X1 sneakers. Engineered for comfort, flexibility, and support.",
    about_ar: "Run faster and longer with our Pro X1 sneakers. Engineered for comfort, flexibility, and support. (نبذة بالعربي)",
    size: "medium",
    color: ["Gray", "Blue", "Black"],
  },
  {
    id: 17,
    category: "Shoes",
    title_en: "Women's Casual Sneakers",
    title_ar: "حذاء كاجوال نسائي",
    price: 59.00,
    oldPrice: 75.00,
    image: "/images/Shoes/Women's Casual Sneakers.webp",
    description_en: "Trendy sneakers with cushioned soles and breathable material. Perfect for everyday walking and outings.",
    description_ar: "Trendy sneakers with cushioned soles and breathable material. Perfect for everyday walking and outings. (وصف عربي)",
    sold: 188,
    rating: 4.6,
    quntity: 22,
    about_en: "Step out in style with these comfy and modern sneakers. Ideal for both casual and sporty looks.",
    about_ar: "Step out in style with these comfy and modern sneakers. Ideal for both casual and sporty looks. (نبذة بالعربي)",
    size: "medium",
    color: ["White", "Pink"],
  },
  {
    id: 18,
    category: "Shoes",
    title_en: "Leather Formal Shoes",
    title_ar: "حذاء رسمي جلدي",
    price: 89.00,
    oldPrice: 109.00,
    image: "/images/Shoes/Leather Formal Shoes.webp",
    description_en: "Premium leather formal shoes with non-slip sole. Ideal for business meetings and special occasions.",
    description_ar: "Premium leather formal shoes with non-slip sole. Ideal for business meetings and special occasions. (وصف عربي)",
    sold: 73,
    rating: 4.8,
    quntity: 12,
    about_en: "Add class and elegance to your formal look. Crafted from genuine leather for superior comfort.",
    about_ar: "Add class and elegance to your formal look. Crafted from genuine leather for superior comfort. (نبذة بالعربي)",
    size: "large",
    color: ["Brown", "Black"],
  },
  {
    id: 19,
    category: "Shoes",
    title_en: "Sports Training Shoes",
    title_ar: "حذاء تدريب رياضي",
    price: 69.00,
    oldPrice: 89.00,
    image: "/images/Shoes/Sports Training Shoes.webp",
    description_en: "Durable sports shoes with flexible sole and cushioned insole. Built for gym, running, and outdoor training.",
    description_ar: "Durable sports shoes with flexible sole and cushioned insole. Built for gym, running, and outdoor training. (وصف عربي)",
    sold: 120,
    rating: 4.7,
    quntity: 18,
    about_en: "Train harder and move freely with these high-performance training shoes.",
    about_ar: "Train harder and move freely with these high-performance training shoes. (نبذة بالعربي)",
    size: "medium",
    color: ["Black", "Orange"],
  },
  {
    id: 20,
    category: "Shoes",
    title_en: "Classic Canvas Sneakers",
    title_ar: "حذاء قماش كلاسيكي",
    price: 39.00,
    oldPrice: 49.00,
    image: "/images/Shoes/Classic Canvas Sneakers.webp",
    description_en: "Timeless canvas sneakers with rubber soles. Lightweight, durable, and easy to match with any outfit.",
    description_ar: "Timeless canvas sneakers with rubber soles. Lightweight, durable, and easy to match with any outfit. (وصف عربي)",
    sold: 204,
    rating: 4.8,
    quntity: 25,
    about_en: "A classic staple that never goes out of style. Perfect for casual wear and everyday comfort.",
    about_ar: "A classic staple that never goes out of style. Perfect for casual wear and everyday comfort. (نبذة بالعربي)",
    size: "medium",
    color: ["White", "Navy"],
  },
  // 👜 Bags & Accessories
{
  id: 101,
  category: "Bags & Accessories",
  title_en: "Leather Crossbody Bag",
    title_ar: "Leather Crossbody Bag (عربي)",
  price: 59.00,
  oldPrice: 75.00,
  image: "/images/Bags & Accessories/Leather Crossbody Bag.webp",
  description_en: "Elegant leather crossbody bag with adjustable strap and multiple compartments. Perfect for travel or daily use. Compact yet spacious design keeps essentials organized with ease.",
    description_ar: "Elegant leather crossbody bag with adjustable strap and multiple compartments. Perfect for travel or daily use. Compact yet spacious design keeps essentials organized with ease. (وصف عربي)",
  sold: 142,
  rating: 4.8,
  quntity: 15,
  about_en: "Experience the perfect balance between fashion and functionality. This leather crossbody bag is crafted with premium materials, offering timeless elegance and durability. Designed for modern lifestyles, it features soft lining, sturdy zippers, and an adjustable strap that ensures comfort all day long.",
    about_ar: "Experience the perfect balance between fashion and functionality. This leather crossbody bag is crafted with premium materials, offering timeless elegance and durability. Designed for modern lifestyles, it features soft lining, sturdy zippers, and an adjustable strap that ensures comfort all day long. (نبذة بالعربي)",
  size: "medium",
  color: ["Brown", "Black"],
},
{
  id: 102,
  category: "Bags & Accessories",
  title_en: "Men’s Classic Wallet",
    title_ar: "Men’s Classic Wallet (عربي)",
  price: 35.00,
  oldPrice: 45.00,
  image: "/images/Bags & Accessories/Men’s Classic Wallet.jpg",
  description_en: "Slim leather wallet with multiple card slots and a smooth finish. Durable and stylish, perfect for everyday use and gifting.",
    description_ar: "Slim leather wallet with multiple card slots and a smooth finish. Durable and stylish, perfect for everyday use and gifting. (وصف عربي)",
  sold: 210,
  rating: 4.6,
  quntity: 25,
  about_en: "Keep your essentials neatly organized in this classic men's wallet. Made from genuine leather with a soft-touch finish, it provides durability and a luxurious feel. The minimalist design easily fits into pockets while offering maximum space for your cards, cash, and ID.",
    about_ar: "Keep your essentials neatly organized in this classic men's wallet. Made from genuine leather with a soft-touch finish, it provides durability and a luxurious feel. The minimalist design easily fits into pockets while offering maximum space for your cards, cash, and ID. (نبذة بالعربي)",
  size: "small",
  color: ["Black", "Dark Brown"],
},
{
  id: 103,
  category: "Bags & Accessories",
  title_en: "Travel Backpack 35L",
    title_ar: "Travel Backpack 35L (عربي)",
  price: 69.00,
  oldPrice: 89.00,
  image: "/images/Bags & Accessories/Travel Backpack 35L.jpg",
  description_en: "Durable travel backpack with 35L capacity, water-resistant fabric, and ergonomic padding for comfort. Great for work, travel, or hiking.",
    description_ar: "Durable travel backpack with 35L capacity, water-resistant fabric, and ergonomic padding for comfort. Great for work, travel, or hiking. (وصف عربي)",
  sold: 188,
  rating: 4.7,
  quntity: 30,
  about_en: "Travel smarter with this 35L backpack designed for comfort and durability. It includes padded straps, multiple compartments, and a laptop sleeve. Made with waterproof materials to keep your belongings safe wherever you go, whether it’s daily commuting or weekend adventures.",
    about_ar: "Travel smarter with this 35L backpack designed for comfort and durability. It includes padded straps, multiple compartments, and a laptop sleeve. Made with waterproof materials to keep your belongings safe wherever you go, whether it’s daily commuting or weekend adventures. (نبذة بالعربي)",
  size: "large",
  color: ["Gray", "Navy Blue"],
},
{
  id: 104,
  category: "Bags & Accessories",
  title_en: "Stylish Sunglasses",
    title_ar: "Stylish Sunglasses (عربي)",
  price: 25.00,
  oldPrice: 35.00,
  image: "/images/Bags & Accessories/Stylish Sunglasses.webp",
  description_en: "Trendy sunglasses with UV400 protection. Lightweight and durable frame suitable for all face shapes. Ideal for daily wear and travel.",
    description_ar: "Trendy sunglasses with UV400 protection. Lightweight and durable frame suitable for all face shapes. Ideal for daily wear and travel. (وصف عربي)",
  sold: 92,
  rating: 4.5,
  quntity: 20,
  about_en: "Protect your eyes with confidence and style. These sunglasses feature UV400 lenses that block harmful rays, ensuring comfort and clear vision. Perfect for fashion lovers who want both functionality and flair.",
    about_ar: "Protect your eyes with confidence and style. These sunglasses feature UV400 lenses that block harmful rays, ensuring comfort and clear vision. Perfect for fashion lovers who want both functionality and flair. (نبذة بالعربي)",
  size: "medium",
  color: ["Black", "Gold"],
},
{
  id: 105,
  category: "Bags & Accessories",
  title_en: "Smart Watch Strap Set",
    title_ar: "Smart Watch Strap Set (عربي)",
  price: 19.99,
  oldPrice: 29.99,
  image: "/images/Bags & Accessories/Smart Watch Strap Set.jpg",
  description_en: "Set of premium silicone straps compatible with most smartwatches. Breathable, flexible, and ideal for sports or daily wear.",
    description_ar: "Set of premium silicone straps compatible with most smartwatches. Breathable, flexible, and ideal for sports or daily wear. (وصف عربي)",
  sold: 77,
  rating: 4.6,
  quntity: 28,
  about_en: "Upgrade your smartwatch style with these premium replacement straps. Made from soft silicone, they provide comfort for all-day wear. Available in multiple colors, designed to fit securely and withstand active lifestyles.",
    about_ar: "Upgrade your smartwatch style with these premium replacement straps. Made from soft silicone, they provide comfort for all-day wear. Available in multiple colors, designed to fit securely and withstand active lifestyles. (نبذة بالعربي)",
  size: "medium",
  color: ["Black", "White", "Red"],
},

// 🍳 Home & Kitchen
{
  id: 201,
  category: "Home & Kitchen",
  title_en: "Electric Kettle 1.8L",
    title_ar: "Electric Kettle 1.8L (عربي)",
  price: 29.00,
  oldPrice: 39.00,
  image: "/images/Home & Kitchen/Electric Kettle 1.8L.webp",
  description_en: "Fast-boil electric kettle with 1.8L capacity and auto shut-off feature. Durable stainless steel body ensures long-lasting use.",
    description_ar: "Fast-boil electric kettle with 1.8L capacity and auto shut-off feature. Durable stainless steel body ensures long-lasting use. (وصف عربي)",
  sold: 320,
  rating: 4.7,
  quntity: 35,
  about_en: "Boil water quickly and safely with this 1.8L electric kettle. Designed with advanced safety features like automatic shut-off and boil-dry protection. The sleek stainless steel design fits perfectly in any modern kitchen.",
    about_ar: "Boil water quickly and safely with this 1.8L electric kettle. Designed with advanced safety features like automatic shut-off and boil-dry protection. The sleek stainless steel design fits perfectly in any modern kitchen. (نبذة بالعربي)",
  size: "medium",
  color: ["Silver", "Black"],
},
{
  id: 202,
  category: "Home & Kitchen",
  title_en: "Ceramic Dinner Set (12 pcs)",
    title_ar: "Ceramic Dinner Set (12 pcs) (عربي)",
  price: 75.00,
  oldPrice: 89.00,
  image: "/images/Home & Kitchen/Ceramic Dinner Set (12 pcs).webp",
  description_en: "Elegant ceramic dinnerware set includes plates, bowls, and mugs. Microwave and dishwasher safe, perfect for daily dining.",
    description_ar: "Elegant ceramic dinnerware set includes plates, bowls, and mugs. Microwave and dishwasher safe, perfect for daily dining. (وصف عربي)",
  sold: 146,
  rating: 4.8,
  quntity: 20,
  about_en: "Upgrade your dining experience with this beautifully designed 12-piece ceramic dinner set. Each piece is crafted to perfection, combining strength, elegance, and ease of cleaning. Perfect for family meals or special occasions.",
    about_ar: "Upgrade your dining experience with this beautifully designed 12-piece ceramic dinner set. Each piece is crafted to perfection, combining strength, elegance, and ease of cleaning. Perfect for family meals or special occasions. (نبذة بالعربي)",
  size: "large",
  color: ["White", "Cream"],
},
{
  id: 203,
  category: "Home & Kitchen",
  title_en: "Stainless Steel Cookware Set",
    title_ar: "Stainless Steel Cookware Set (عربي)",
  price: 99.00,
  oldPrice: 119.00,
  image: "/images/Home & Kitchen/Stainless Steel Cookware Set.avif",
  description_en: "Complete cookware set with non-stick coating. Includes pots, pans, and lids. Durable and heat-resistant for all stovetops.",
    description_ar: "Complete cookware set with non-stick coating. Includes pots, pans, and lids. Durable and heat-resistant for all stovetops. (وصف عربي)",
  sold: 208,
  rating: 4.6,
  quntity: 18,
  about_en: "Cook like a professional with this stainless steel cookware set. Designed for maximum durability and even heat distribution. Whether you’re simmering sauces or frying vegetables, this set delivers reliable results every time.",
    about_ar: "Cook like a professional with this stainless steel cookware set. Designed for maximum durability and even heat distribution. Whether you’re simmering sauces or frying vegetables, this set delivers reliable results every time. (نبذة بالعربي)",
  size: "large",
  color: ["Silver"],
},
{
  id: 204,
  category: "Home & Kitchen",
  title_en: "Air Fryer 5L",
    title_ar: "Air Fryer 5L (عربي)",
  price: 89.00,
  oldPrice: 110.00,
  image: "/images/Home & Kitchen/Air Fryer 5L.jpg",
  description_en: "Healthy air fryer with 5L capacity and digital controls. Enjoy crispy results using up to 85% less oil. Easy to clean and safe to use.",
    description_ar: "Healthy air fryer with 5L capacity and digital controls. Enjoy crispy results using up to 85% less oil. Easy to clean and safe to use. (وصف عربي)",
  sold: 270,
  rating: 4.9,
  quntity: 25,
  about_en: "Enjoy delicious meals with less oil using this powerful 5L air fryer. Featuring digital temperature control, timer, and removable non-stick basket, it makes healthy cooking faster and easier than ever.",
    about_ar: "Enjoy delicious meals with less oil using this powerful 5L air fryer. Featuring digital temperature control, timer, and removable non-stick basket, it makes healthy cooking faster and easier than ever. (نبذة بالعربي)",
  size: "medium",
  color: ["Black", "White"],
},
{
  id: 205,
  category: "Home & Kitchen",
  title_en: "Smart LED Lamp",
    title_ar: "Smart LED Lamp (عربي)",
  price: 35.00,
  oldPrice: 45.00,
  image: "/images/Home & Kitchen/Smart LED Lamp.png",
  description_en: "Modern smart LED lamp with adjustable brightness and color modes. Controlled via app or touch panel. Energy-efficient and elegant.",
    description_ar: "Modern smart LED lamp with adjustable brightness and color modes. Controlled via app or touch panel. Energy-efficient and elegant. (وصف عربي)",
  sold: 115,
  rating: 4.7,
  quntity: 22,
  about_en: "Light up your home with innovation. The Smart LED Lamp offers adjustable color temperatures, remote app control, and voice compatibility with Alexa and Google Home. Perfect for bedrooms, offices, or cozy reading corners.",
    about_ar: "Light up your home with innovation. The Smart LED Lamp offers adjustable color temperatures, remote app control, and voice compatibility with Alexa and Google Home. Perfect for bedrooms, offices, or cozy reading corners. (نبذة بالعربي)",
  size: "medium",
  color: ["White", "Silver"],
},

// 💄 Beauty & Cosmetics
{
  id: 301,
  category: "Beauty & Cosmetics",
  title_en: "Matte Liquid Lipstick Set",
    title_ar: "Matte Liquid Lipstick Set (عربي)",
  price: 25.00,
  oldPrice: 35.00,
  image: "/images/Beauty & Cosmetics/Matte Liquid Lipstick Set.webp",
  description_en: "Long-lasting matte liquid lipstick with rich pigmentation. Non-drying formula for smooth and comfortable wear all day.",
    description_ar: "Long-lasting matte liquid lipstick with rich pigmentation. Non-drying formula for smooth and comfortable wear all day. (وصف عربي)",
  sold: 210,
  rating: 4.8,
  quntity: 40,
  about_en: "Get bold, beautiful lips with our Matte Liquid Lipstick Set. The creamy texture glides effortlessly and sets into a smooth matte finish. Available in multiple shades, each designed to enhance your natural beauty and confidence.",
    about_ar: "Get bold, beautiful lips with our Matte Liquid Lipstick Set. The creamy texture glides effortlessly and sets into a smooth matte finish. Available in multiple shades, each designed to enhance your natural beauty and confidence. (نبذة بالعربي)",
  size: "small",
  color: ["Red", "Nude", "Pink"],
},
{
  id: 302,
  category: "Beauty & Cosmetics",
  title_en: "Hydrating Face Serum",
    title_ar: "Hydrating Face Serum (عربي)",
  price: 39.00,
  oldPrice: 49.00,
  image: "/images/Beauty & Cosmetics/Hydrating Face Serum.webp",
  description_en: "Deep-hydrating serum enriched with hyaluronic acid and vitamin C. Brightens and revitalizes dull, tired skin for a radiant look.",
    description_ar: "Deep-hydrating serum enriched with hyaluronic acid and vitamin C. Brightens and revitalizes dull, tired skin for a radiant look. (وصف عربي)",
  sold: 182,
  rating: 4.9,
  quntity: 28,
  about_en: "Revitalize your skin with this luxurious hydrating serum. Infused with powerful antioxidants and nutrients, it restores moisture balance and boosts elasticity. Perfect for all skin types, leaving your complexion smoother and more luminous.",
    about_ar: "Revitalize your skin with this luxurious hydrating serum. Infused with powerful antioxidants and nutrients, it restores moisture balance and boosts elasticity. Perfect for all skin types, leaving your complexion smoother and more luminous. (نبذة بالعربي)",
  size: "small",
  color: ["Transparent"],
},
{
  id: 303,
  category: "Beauty & Cosmetics",
  title_en: "Compact Foundation Powder",
    title_ar: "Compact Foundation Powder (عربي)",
  price: 32.00,
  oldPrice: 42.00,
  image: "/images/Beauty & Cosmetics/Compact Foundation Powder.jpg",
  description_en: "Lightweight foundation powder provides flawless coverage with a natural matte finish. Suitable for all skin tones.",
    description_ar: "Lightweight foundation powder provides flawless coverage with a natural matte finish. Suitable for all skin tones. (وصف عربي)",
  sold: 130,
  rating: 4.6,
  quntity: 35,
  about_en: "Achieve a flawless complexion with this silky foundation powder. Its lightweight formula blends easily, controlling shine and smoothing out imperfections while allowing your skin to breathe naturally.",
    about_ar: "Achieve a flawless complexion with this silky foundation powder. Its lightweight formula blends easily, controlling shine and smoothing out imperfections while allowing your skin to breathe naturally. (نبذة بالعربي)",
  size: "medium",
  color: ["Beige", "Ivory"],
},
{
  id: 304,
  category: "Beauty & Cosmetics",
  title_en: "Volumizing Mascara",
    title_ar: "Volumizing Mascara (عربي)",
  price: 19.00,
  oldPrice: 25.00,
  image: "/images/Beauty & Cosmetics/Volumizing Mascara.webp",
  description_en: "Waterproof volumizing mascara with intense black pigment. Lifts and defines lashes for a dramatic, long-lasting look.",
    description_ar: "Waterproof volumizing mascara with intense black pigment. Lifts and defines lashes for a dramatic, long-lasting look. (وصف عربي)",
  sold: 174,
  rating: 4.7,
  quntity: 30,
  about_en: "Transform your lashes with instant volume and definition. This mascara’s advanced formula adds body without clumps and resists smudging, keeping your eyes looking captivating all day.",
    about_ar: "Transform your lashes with instant volume and definition. This mascara’s advanced formula adds body without clumps and resists smudging, keeping your eyes looking captivating all day. (نبذة بالعربي)",
  size: "small",
  color: ["Black"],
},
{
  id: 305,
  category: "Beauty & Cosmetics",
  title_en: "Aloe Vera Moisturizing Cream",
    title_ar: "Aloe Vera Moisturizing Cream (عربي)",
  price: 22.00,
  oldPrice: 30.00,
  image: "/images/Beauty & Cosmetics/Aloe Vera Moisturizing Cream.jpg",
  description_en: "Natural aloe vera cream deeply moisturizes and soothes the skin. Gentle, fast-absorbing, and suitable for daily use.",
    description_ar: "Natural aloe vera cream deeply moisturizes and soothes the skin. Gentle, fast-absorbing, and suitable for daily use. (وصف عربي)",
  sold: 196,
  rating: 4.8,
  quntity: 40,
  about_en: "Enjoy soft, refreshed skin with this aloe-based moisturizing cream. It nourishes, hydrates, and soothes irritation while protecting against dryness. Ideal for sensitive and normal skin alike, leaving a lasting glow.",
    about_ar: "Enjoy soft, refreshed skin with this aloe-based moisturizing cream. It nourishes, hydrates, and soothes irritation while protecting against dryness. Ideal for sensitive and normal skin alike, leaving a lasting glow. (نبذة بالعربي)",
  size: "medium",
  color: ["Green", "White"],
},
// 🏃 Sports & Outdoors
{
  id: 401,
  category: "Sports & Outdoors",
  title_en: "Mountain Bike Pro 26”",
    title_ar: "Mountain Bike Pro 26” (عربي)",
  price: 299.00,
  oldPrice: 349.00,
  image: "/images/Sports & Outdoors/Mountain Bike Pro 26.jpg",
  description_en: "Durable 26-inch mountain bike with alloy frame and shock-absorbing suspension. Ideal for trails, hills, and daily commuting.",
    description_ar: "Durable 26-inch mountain bike with alloy frame and shock-absorbing suspension. Ideal for trails, hills, and daily commuting. (وصف عربي)",
  sold: 112,
  rating: 4.7,
  quntity: 10,
  about_en: "Conquer every terrain with this professional-grade mountain bike. Its lightweight yet sturdy frame ensures durability, while advanced suspension absorbs impact for a smooth ride. Perfect for outdoor enthusiasts who crave adventure and performance.",
    about_ar: "Conquer every terrain with this professional-grade mountain bike. Its lightweight yet sturdy frame ensures durability, while advanced suspension absorbs impact for a smooth ride. Perfect for outdoor enthusiasts who crave adventure and performance. (نبذة بالعربي)",
  size: "large",
  color: ["Red", "Black"],
},
{
  id: 402,
  category: "Sports & Outdoors",
  title_en: "Yoga Mat Pro Grip",
    title_ar: "Yoga Mat Pro Grip (عربي)",
  price: 35.00,
  oldPrice: 45.00,
  image: "/images/Sports & Outdoors/Yoga Mat Pro Grip.jpg",
  description_en: "Eco-friendly yoga mat with anti-slip surface and thick cushioning. Provides stability and comfort for all yoga levels.",
    description_ar: "Eco-friendly yoga mat with anti-slip surface and thick cushioning. Provides stability and comfort for all yoga levels. (وصف عربي)",
  sold: 168,
  rating: 4.8,
  quntity: 20,
  about_en: "Enhance your yoga practice with this premium mat that combines comfort, grip, and durability. Made from non-toxic, eco-safe materials, it offers excellent support and balance for all poses.",
    about_ar: "Enhance your yoga practice with this premium mat that combines comfort, grip, and durability. Made from non-toxic, eco-safe materials, it offers excellent support and balance for all poses. (نبذة بالعربي)",
  size: "medium",
  color: ["Purple", "Blue", "Green"],
},
{
  id: 403,
  category: "Sports & Outdoors",
  title_en: "Adjustable Dumbbell Set 20kg",
    title_ar: "Adjustable Dumbbell Set 20kg (عربي)",
  price: 89.00,
  oldPrice: 109.00,
  image: "/images/Sports & Outdoors/Adjustable Dumbbell Set 20kg.jpg",
  description_en: "Adjustable dumbbell set up to 20kg with non-slip handles. Perfect for home workouts and strength training.",
    description_ar: "Adjustable dumbbell set up to 20kg with non-slip handles. Perfect for home workouts and strength training. (وصف عربي)",
  sold: 132,
  rating: 4.7,
  quntity: 18,
  about_en: "Transform your home into a personal gym with this compact dumbbell set. Easily adjustable for various exercises, helping you build muscle and stay fit without bulky equipment.",
    about_ar: "Transform your home into a personal gym with this compact dumbbell set. Easily adjustable for various exercises, helping you build muscle and stay fit without bulky equipment. (نبذة بالعربي)",
  size: "medium",
  color: ["Black"],
},
{
  id: 404,
  category: "Sports & Outdoors",
  title_en: "Waterproof Sports Watch",
    title_ar: "Waterproof Sports Watch (عربي)",
  price: 49.00,
  oldPrice: 65.00,
  image: "/images/Sports & Outdoors/Waterproof Sports Watch.jpg",
  description_en: "Rugged waterproof sports watch with stopwatch and heart-rate tracker. Built for endurance and outdoor activity.",
    description_ar: "Rugged waterproof sports watch with stopwatch and heart-rate tracker. Built for endurance and outdoor activity. (وصف عربي)",
  sold: 94,
  rating: 4.6,
  quntity: 22,
  about_en: "Stay active and on time with this multifunctional sports watch. Designed for outdoor enthusiasts, it combines durability, waterproofing, and smart tracking to support your fitness goals.",
    about_ar: "Stay active and on time with this multifunctional sports watch. Designed for outdoor enthusiasts, it combines durability, waterproofing, and smart tracking to support your fitness goals. (نبذة بالعربي)",
  size: "medium",
  color: ["Black", "Blue"],
},
{
  id: 405,
  category: "Sports & Outdoors",
  title_en: "Camping Tent 4-Person",
    title_ar: "Camping Tent 4-Person (عربي)",
  price: 129.00,
  oldPrice: 149.00,
  image: "/images/Sports & Outdoors/Camping Tent 4-Person.jpg",
  description_en: "Spacious 4-person tent with weather-resistant fabric and quick setup system. Ideal for camping and outdoor trips.",
    description_ar: "Spacious 4-person tent with weather-resistant fabric and quick setup system. Ideal for camping and outdoor trips. (وصف عربي)",
  sold: 77,
  rating: 4.8,
  quntity: 12,
  about_en: "Enjoy your outdoor adventures with this easy-to-assemble camping tent. It provides excellent ventilation, waterproof protection, and enough space for the whole family. Perfect for weekend getaways or hiking trips.",
    about_ar: "Enjoy your outdoor adventures with this easy-to-assemble camping tent. It provides excellent ventilation, waterproof protection, and enough space for the whole family. Perfect for weekend getaways or hiking trips. (نبذة بالعربي)",
  size: "large",
  color: ["Green", "Gray"],
},

// 🧸 Toys & Games
{
  id: 501,
  category: "Toys & Games",
  title_en: "Building Blocks Set 120pcs",
    title_ar: "Building Blocks Set 120pcs (عربي)",
  price: 29.00,
  oldPrice: 39.00,
  image: "/images/Toys & Games/Building Blocks Set 120pcs.jpg",
  description_en: "Colorful building block set that encourages creativity and motor skills in kids. Safe, durable, and easy to clean.",
    description_ar: "Colorful building block set that encourages creativity and motor skills in kids. Safe, durable, and easy to clean. (وصف عربي)",
  sold: 216,
  rating: 4.9,
  quntity: 30,
  about_en: "Spark imagination and creativity with this large building block set. Designed for safety and fun, it helps children develop problem-solving and coordination skills through play.",
    about_ar: "Spark imagination and creativity with this large building block set. Designed for safety and fun, it helps children develop problem-solving and coordination skills through play. (نبذة بالعربي)",
  size: "large",
  color: ["Multicolor"],
},
{
  id: 502,
  category: "Toys & Games",
  title_en: "Remote Control Car Turbo X",
    title_ar: "Remote Control Car Turbo X (عربي)",
  price: 45.00,
  oldPrice: 59.00,
  image: "/images/Toys & Games/Remote Control Car Turbo X.jpg",
  description_en: "High-speed remote control car with rechargeable battery and durable frame. Perfect for indoor and outdoor racing.",
    description_ar: "High-speed remote control car with rechargeable battery and durable frame. Perfect for indoor and outdoor racing. (وصف عربي)",
  sold: 178,
  rating: 4.7,
  quntity: 18,
  about_en: "Race into excitement with the Turbo X RC Car. Featuring fast acceleration, responsive controls, and tough design, it delivers endless fun for both kids and adults.",
    about_ar: "Race into excitement with the Turbo X RC Car. Featuring fast acceleration, responsive controls, and tough design, it delivers endless fun for both kids and adults. (نبذة بالعربي)",
  size: "medium",
  color: ["Red", "Blue"],
},
{
  id: 503,
  category: "Toys & Games",
  title_en: "Educational Puzzle Set",
    title_ar: "Educational Puzzle Set (عربي)",
  price: 19.99,
  oldPrice: 25.00,
  image: "/images/Toys & Games/Educational Puzzle Set.webp",
  description_en: "Colorful educational puzzle designed to develop logic and learning skills in young children. Safe and eco-friendly material.",
    description_ar: "Colorful educational puzzle designed to develop logic and learning skills in young children. Safe and eco-friendly material. (وصف عربي)",
  sold: 153,
  rating: 4.8,
  quntity: 25,
  about_en: "Make learning fun with this interactive puzzle set. Encourages cognitive growth and problem-solving in a playful way, perfect for preschoolers and early learners.",
    about_ar: "Make learning fun with this interactive puzzle set. Encourages cognitive growth and problem-solving in a playful way, perfect for preschoolers and early learners. (نبذة بالعربي)",
  size: "medium",
  color: ["Multicolor"],
},
{
  id: 504,
  category: "Toys & Games",
  title_en: "Plush Teddy Bear 60cm",
    title_ar: "Plush Teddy Bear 60cm (عربي)",
  price: 35.00,
  oldPrice: 49.00,
  image: "/images/Toys & Games/Plush Teddy Bear 60cm.webp",
  description_en: "Soft and cuddly teddy bear made with premium plush material. A perfect gift for kids or loved ones.",
    description_ar: "Soft and cuddly teddy bear made with premium plush material. A perfect gift for kids or loved ones. (وصف عربي)",
  sold: 201,
  rating: 4.9,
  quntity: 15,
  about_en: "Bring smiles and warmth with this adorable plush teddy bear. Its ultra-soft fur and huggable size make it a comforting companion for kids and collectors alike.",
    about_ar: "Bring smiles and warmth with this adorable plush teddy bear. Its ultra-soft fur and huggable size make it a comforting companion for kids and collectors alike. (نبذة بالعربي)",
  size: "large",
  color: ["Brown", "Cream"],
},
{
  id: 505,
  category: "Toys & Games",
  title_en: "Kids Drawing Kit Deluxe",
    title_ar: "Kids Drawing Kit Deluxe (عربي)",
  price: 28.00,
  oldPrice: 35.00,
  image: "/images/Toys & Games/Kids Drawing Kit Deluxe.avif",
  description_en: "Complete art kit with crayons, markers, and sketchbook. Encourages creativity and fine motor development.",
    description_ar: "Complete art kit with crayons, markers, and sketchbook. Encourages creativity and fine motor development. (وصف عربي)",
  sold: 145,
  rating: 4.7,
  quntity: 22,
  about_en: "Unleash your child's artistic talent with this all-in-one drawing kit. Includes high-quality tools designed for safe, endless creativity and fun.",
    about_ar: "Unleash your child's artistic talent with this all-in-one drawing kit. Includes high-quality tools designed for safe, endless creativity and fun. (نبذة بالعربي)",
  size: "medium",
  color: ["Multicolor"],
},

// 📚 Books & Stationery
{
  id: 601,
  category: "Books & Stationery",
  title_en: "Classic Notebook A5",
    title_ar: "Classic Notebook A5 (عربي)",
  price: 9.99,
  oldPrice: 15.00,
  image: "/images/Books & Stationery/Classic Notebook A5.jpg",
  description_en: "Premium ruled notebook with thick pages and leather cover. Ideal for journaling, note-taking, or planning.",
    description_ar: "Premium ruled notebook with thick pages and leather cover. Ideal for journaling, note-taking, or planning. (وصف عربي)",
  sold: 310,
  rating: 4.9,
  quntity: 50,
  about_en: "Keep your thoughts and ideas organized with this elegant A5 notebook. Crafted with durable cover and smooth pages for a pleasant writing experience, perfect for students and professionals.",
    about_ar: "Keep your thoughts and ideas organized with this elegant A5 notebook. Crafted with durable cover and smooth pages for a pleasant writing experience, perfect for students and professionals. (نبذة بالعربي)",
  size: "small",
  color: ["Black", "Brown"],
},
{
  id: 602,
  category: "Books & Stationery",
  title_en: "Gel Pen Set (12 Colors)",
    title_ar: "Gel Pen Set (12 Colors) (عربي)",
  price: 12.00,
  oldPrice: 18.00,
  image: "/images/Books & Stationery/Gel Pen Set (12 Colors).webp",
  description_en: "Smooth-writing gel pens in 12 vibrant colors. Quick-drying ink ideal for school, art, or office work.",
    description_ar: "Smooth-writing gel pens in 12 vibrant colors. Quick-drying ink ideal for school, art, or office work. (وصف عربي)",
  sold: 184,
  rating: 4.8,
  quntity: 40,
  about_en: "Add color to your notes with these smooth-flowing gel pens. Designed for precision and comfort, the pens feature fade-resistant ink perfect for creative projects and daily use.",
    about_ar: "Add color to your notes with these smooth-flowing gel pens. Designed for precision and comfort, the pens feature fade-resistant ink perfect for creative projects and daily use. (نبذة بالعربي)",
  size: "small",
  color: ["Multicolor"],
},
{
  id: 603,
  category: "Books & Stationery",
  title_en: "Desk Organizer Set",
    title_ar: "Desk Organizer Set (عربي)",
  price: 29.00,
  oldPrice: 35.00,
  image: "/images/Books & Stationery/Desk Organizer Set.avif",
  description_en: "Stylish desk organizer set with multiple compartments. Keeps your workspace tidy and efficient.",
    description_ar: "Stylish desk organizer set with multiple compartments. Keeps your workspace tidy and efficient. (وصف عربي)",
  sold: 123,
  rating: 4.7,
  quntity: 18,
  about_en: "Keep your desk clutter-free with this modern organizer set. Crafted from durable materials, it’s perfect for storing pens, papers, and accessories in style.",
    about_ar: "Keep your desk clutter-free with this modern organizer set. Crafted from durable materials, it’s perfect for storing pens, papers, and accessories in style. (نبذة بالعربي)",
  size: "medium",
  color: ["Black", "Gray"],
},
{
  id: 604,
  category: "Books & Stationery",
  title_en: "Inspirational Quote Journal",
    title_ar: "Inspirational Quote Journal (عربي)",
  price: 14.99,
  oldPrice: 20.00,
  image: "/images/Books & Stationery/Inspirational Quote Journal.webp",
  description_en: "Motivational journal with 200 lined pages and inspiring quotes. Great for reflection and daily writing.",
    description_ar: "Motivational journal with 200 lined pages and inspiring quotes. Great for reflection and daily writing. (وصف عربي)",
  sold: 167,
  rating: 4.9,
  quntity: 25,
  about_en: "Start every day inspired with this motivational journal. Each page features an uplifting quote to keep you focused and positive as you write your thoughts and goals.",
    about_ar: "Start every day inspired with this motivational journal. Each page features an uplifting quote to keep you focused and positive as you write your thoughts and goals. (نبذة بالعربي)",
  size: "small",
  color: ["White", "Gold"],
},
{
  id: 605,
  category: "Books & Stationery",
  title_en: "Study Lamp Foldable LED",
    title_ar: "Study Lamp Foldable LED (عربي)",
  price: 22.00,
  oldPrice: 30.00,
  image: "/images/Books & Stationery/Study Lamp Foldable LED.jpg",
  description_en: "Foldable LED lamp with adjustable brightness and USB charging. Perfect for study or work desks.",
    description_ar: "Foldable LED lamp with adjustable brightness and USB charging. Perfect for study or work desks. (وصف عربي)",
  sold: 99,
  rating: 4.6,
  quntity: 20,
  about_en: "Illuminate your study space with this compact and efficient LED lamp. It features adjustable angles, soft light, and energy-saving design for long hours of reading or work.",
    about_ar: "Illuminate your study space with this compact and efficient LED lamp. It features adjustable angles, soft light, and energy-saving design for long hours of reading or work. (نبذة بالعربي)",
  size: "medium",
  color: ["White", "Silver"],
},

// 🪑 Furniture
{
  id: 701,
  category: "Furniture",
  title_en: "Modern Office Chair",
    title_ar: "Modern Office Chair (عربي)",
  price: 129.00,
  oldPrice: 159.00,
  image: "/images/Furniture/Modern Office Chair.avif",
  description_en: "Ergonomic office chair with lumbar support and adjustable height. Breathable mesh for all-day comfort.",
    description_ar: "Ergonomic office chair with lumbar support and adjustable height. Breathable mesh for all-day comfort. (وصف عربي)",
  sold: 87,
  rating: 4.7,
  quntity: 10,
  about_en: "Work in comfort with this modern office chair designed to support your posture. Its ergonomic features help reduce strain and enhance productivity, making it ideal for long working hours.",
    about_ar: "Work in comfort with this modern office chair designed to support your posture. Its ergonomic features help reduce strain and enhance productivity, making it ideal for long working hours. (نبذة بالعربي)",
  size: "large",
  color: ["Black", "Gray"],
},
{
  id: 702,
  category: "Furniture",
  title_en: "Wooden Coffee Table",
    title_ar: "Wooden Coffee Table (عربي)",
  price: 99.00,
  oldPrice: 120.00,
  image: "/images/Furniture/Wooden Coffee Table.jpeg",
  description_en: "Elegant wooden coffee table with smooth finish and sturdy legs. Perfect centerpiece for your living room.",
    description_ar: "Elegant wooden coffee table with smooth finish and sturdy legs. Perfect centerpiece for your living room. (وصف عربي)",
  sold: 65,
  rating: 4.6,
  quntity: 8,
  about_en: "Add warmth and elegance to your home with this handcrafted wooden coffee table. Built from premium wood with a natural finish that complements any modern or classic décor.",
    about_ar: "Add warmth and elegance to your home with this handcrafted wooden coffee table. Built from premium wood with a natural finish that complements any modern or classic décor. (نبذة بالعربي)",
  size: "large",
  color: ["Brown", "Walnut"],
},
{
  id: 703,
  category: "Furniture",
  title_en: "Minimalist Bookshelf 5-Tier",
    title_ar: "Minimalist Bookshelf 5-Tier (عربي)",
  price: 139.00,
  oldPrice: 165.00,
  image: "/images/Furniture/Minimalist Bookshelf 5-Tier.webp",
  description_en: "5-tier bookshelf made from solid wood with a modern minimalist design. Great for books or decorative items.",
    description_ar: "5-tier bookshelf made from solid wood with a modern minimalist design. Great for books or decorative items. (وصف عربي)",
  sold: 48,
  rating: 4.8,
  quntity: 6,
  about_en: "Display your books and treasures in style with this minimalist 5-tier bookshelf. Sturdy, elegant, and space-efficient — perfect for living rooms, offices, or bedrooms.",
    about_ar: "Display your books and treasures in style with this minimalist 5-tier bookshelf. Sturdy, elegant, and space-efficient — perfect for living rooms, offices, or bedrooms. (نبذة بالعربي)",
  size: "large",
  color: ["Oak", "White"],
},
{
  id: 704,
  category: "Furniture",
  title_en: "Queen Size Bed Frame",
    title_ar: "Queen Size Bed Frame (عربي)",
  price: 299.00,
  oldPrice: 349.00,
  image: "/images/Furniture/Queen Size Bed Frame.avif",
  description_en: "Sturdy queen size bed frame with upholstered headboard and solid wooden slats. Easy to assemble and durable.",
    description_ar: "Sturdy queen size bed frame with upholstered headboard and solid wooden slats. Easy to assemble and durable. (وصف عربي)",
  sold: 52,
  rating: 4.7,
  quntity: 5,
  about_en: "Upgrade your bedroom comfort with this modern queen bed frame. Designed for durability and luxury, it combines strong materials with an elegant aesthetic.",
    about_ar: "Upgrade your bedroom comfort with this modern queen bed frame. Designed for durability and luxury, it combines strong materials with an elegant aesthetic. (نبذة بالعربي)",
  size: "large",
  color: ["Gray", "Beige"],
},
{
  id: 705,
  category: "Furniture",
  title_en: "Dining Chair Set (4 pcs)",
    title_ar: "Dining Chair Set (4 pcs) (عربي)",
  price: 249.00,
  oldPrice: 279.00,
  image: "/images/Furniture/Dining Chair Set (4 pcs).jpeg",
  description_en: "Set of four dining chairs with cushioned seats and ergonomic backrest. Built for comfort and modern aesthetics.",
    description_ar: "Set of four dining chairs with cushioned seats and ergonomic backrest. Built for comfort and modern aesthetics. (وصف عربي)",
  sold: 73,
  rating: 4.8,
  quntity: 7,
  about_en: "Dine in style and comfort with this premium 4-piece chair set. The modern design blends beautifully with any interior, offering both durability and luxurious seating experience.",
    about_ar: "Dine in style and comfort with this premium 4-piece chair set. The modern design blends beautifully with any interior, offering both durability and luxurious seating experience. (نبذة بالعربي)",
  size: "large",
  color: ["Beige", "Black"],
},


];

export default products;
